### ISSUE TITLE
Don't use `new vscode.TextEdit.replace`

### ISSUE THREAD

**Issue by jrieken** [mikeburgh/vscode-xml-format#5]
The `vscode.TextEdit.replace`-function is a static member of the `TextEditr`-class. Calling it with `new` was only possible because vscode used to compile its TypeScript sources to ES5, not ES6. Now calling a static class function using the `new`-keyword isn't possible anymore and results in an error (like [Microsoft/vscode#69533](https://github.com/Microsoft/vscode/issues/69533)).

Please update and use `vscode.TextEdit.replace` without the `new` keyword.

Thanks and HappyCoding!

**Comment by mikeburgh** [comment]
Thanks, that's been fixed and new version published!
